### ISSUE TITLE
Package add-ons into Pro version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#101]
The 6 individual packages are here on Github. We'll release them in one Pro version:
https://github.com/search?q=org%3Apublishpress+organize

<img width="419" alt="Screen Shot 2021-08-05 at 4 07 29 PM" src="https://user-images.githubusercontent.com/3868028/128414982-51ef7140-999c-4b5e-b7c7-51f79595a778.png">

**Comment by olatechpro** [comment]
All the add-ons needed to be handle separately
