### ISSUE TITLE
Enable / Disable Features setting

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#102]
The Pro version needs the option to enable / disable features, because one should only be disabled by default:

<img width="921" alt="Screen Shot 2021-08-09 at 9 54 31 AM" src="https://user-images.githubusercontent.com/3868028/128717850-e7a28ffd-c9b2-4bf9-a1d9-80a517ec3b35.png">

**Comment by olatechpro** [comment]
Pro fix (https://github.com/publishpress/publishpress-series-pro/pull/12)
