### ISSUE TITLE
License key set up

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#103]
It looks like the plugin already has some EDD integration:

<img width="305" alt="Screen Shot 2021-08-09 at 9 57 35 AM" src="https://user-images.githubusercontent.com/3868028/128718325-a24493d5-02ee-41a0-85d3-94fffb6e1892.png">

**Comment by olatechpro** [comment]
We can't use this since it's for different addon and we only need a single licence entry for the PRO version or is licence key for each addon in pro version ? @stevejburge

**Comment by stevejburge** [comment]
@olatechpro No worries, then. We can remove that old code

**Comment by olatechpro** [comment]
Pro fix (https://github.com/publishpress/publishpress-series-pro/pull/13)
