### ISSUE TITLE
PublishPress Series Screen is blank in Pro

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#124]
This is only the Pro version:
<img width="593" alt="Screen Shot 2021-08-13 at 4 22 42 PM" src="https://user-images.githubusercontent.com/3868028/129414647-1a0213e5-3fe0-49db-b743-df149ef005dc.png">

Free looks great:
<img width="1239" alt="Screen Shot 2021-08-13 at 4 30 22 PM" src="https://user-images.githubusercontent.com/3868028/129415282-686acfa1-3677-4be0-81b8-49a3905199e5.png">

**Comment by olatechpro** [comment]
Hi @steve, have you added any series in Manage series ? Else, the page will be blank as it's the page created by 'Series publish addon' to show all series with publish bulk action

Check 'Settings' > 'Series options' for more.

**Comment by stevejburge** [comment]
Ah, I see it now, thanks. 

I had to disable the Pro plugin, then activate again, and extra menu links appeared

**Comment by olatechpro** [comment]
Also, in the Pro screenshot you shared, I noticed 'manage series' is missing under the post menu.

Make sure you didn't deselect 'post' under post type integration in settings so it can be there. @stevejburge

**Comment by stevejburge** [comment]
Thanks. I'll test more
