### ISSUE TITLE
add a message for the empty "Publish Series" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#125]
Let's add a message for the empty "Publish Series" screen:
"You have no series available to publish"
<img width="778" alt="Screen Shot 2021-08-14 at 12 07 00 PM" src="https://user-images.githubusercontent.com/3868028/129452419-971aad86-4edc-47aa-95e4-be3947218c1d.png">

**Comment by olatechpro** [comment]
Pro fix (https://github.com/publishpress/publishpress-series-pro/pull/14)
