### ISSUE TITLE
Remove "Group" box from Add New Series page

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#127]
This box hides key features and isn't needed

<img width="859" alt="Screen Shot 2021-08-14 at 12 12 10 PM" src="https://user-images.githubusercontent.com/3868028/129452534-45cd21ae-0c71-433e-8405-d62b188adc73.png">

**Comment by olatechpro** [comment]
Hi @steve, by asking to remove from 'add series page', that include edit series page right ?

...and if so, are you aware it was added by 'Series Grouping' add-on ?

So, does that mean we're removing the add-on from pro ?

That aside, what do you mean by it's hiding key features, if it's and overlapping, we can fix that but if you feel the add-on is not useful, then we can remove it from pro ?

@stevejburge

**Comment by stevejburge** [comment]
@olatechpro Sorry, I should have been clearer. 

I think we should just remove this box.

There are other ways to add series to groups. For example:

<img width="596" alt="Screen Shot 2021-08-16 at 8 30 10 AM" src="https://user-images.githubusercontent.com/3868028/129564088-df4ac520-220a-4cda-9641-ea84cdb63919.png">

**Comment by olatechpro** [comment]
So, we're removing the metabox from add and edit series right 

Leaving it only for quick edit. 

@stevejburge

**Comment by stevejburge** [comment]
@olatechpro Yes, although perhaps an alternative to make this metabox much smaller and less obtrusive.

Is that better? Just make this box much cleaner?

**Comment by olatechpro** [comment]
Pro fix (https://github.com/publishpress/publishpress-series-pro/pull/15)
