### ISSUE TITLE
Settings cleanup

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#129]
Can we add WordPress default tabs for the Settings area?

"General"

<img width="1034" alt="Screen Shot 2021-08-14 at 12 24 23 PM" src="https://user-images.githubusercontent.com/3868028/129452857-e7a35cf7-d2e8-4558-8d71-ca6ef94c68aa.png">

"Post Types"

<img width="1025" alt="Screen Shot 2021-08-14 at 12 23 04 PM" src="https://user-images.githubusercontent.com/3868028/129452838-42d95272-e6b9-42ff-9277-4368fa237c04.png">

"Icons"

<img width="832" alt="Screen Shot 2021-08-14 at 12 25 15 PM" src="https://user-images.githubusercontent.com/3868028/129452871-278eeb65-da85-4d43-856b-c9e83dbbabc7.png">

"Templates"

<img width="1042" alt="Screen Shot 2021-08-14 at 12 24 54 PM" src="https://user-images.githubusercontent.com/3868028/129452880-43a334ed-d70f-4051-9d02-f8fde8d31200.png">

"Pro Features"

<img width="1059" alt="Screen Shot 2021-08-14 at 12 22 21 PM" src="https://user-images.githubusercontent.com/3868028/129452816-a06381f9-ca7b-47af-9bc5-c278bbcf1356.png">

**Comment by olatechpro** [comment]
@stevejburge, what do you mean by WordPress default tab or you're referring to as in the screenshot below? 

![128318137-83643e9b-c8d1-4128-8ce8-1c03cc0c6c95_1](https://user-images.githubusercontent.com/46832636/129454918-728fccd4-44a6-4f7f-b7d2-55c68b3aa893.png)

**Comment by stevejburge** [comment]
Sorry, tab like these:

![Screen Shot 2021-08-14 at 1 11 34 PM](https://user-images.githubusercontent.com/3868028/129455072-c5a9b7b5-e643-4812-bc77-4a374bf5c7b0.png)
