### ISSUE TITLE
General tab changes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#136]
Let's turn this into a regular settings area. We don't need the small text, or the italics:

![Screen Shot 2021-08-16 at 1 26 33 PM](https://user-images.githubusercontent.com/3868028/129604927-016ed6a7-bfbd-4e0f-aff5-d2d2ad464c37.png)

**Comment by olatechpro** [comment]
Hi @stevejburge , 

1.) can you be more specific with what you mean by "Turn into regular options" ?

2.) By "We don't need the small text, or the italics", do you mean i should remove all fields description for all tabs fields or just the general tabs alone and have you really checked and confirm some of these fields doesn't really need an explanation description like "Pro features tab Enable Features checkboxes", templates tab and others ?

**Comment by stevejburge** [comment]
@olatechpro Compare the image above to a normal setting screen:

<img width="502" alt="Screen Shot 2021-08-17 at 11 32 43 AM" src="https://user-images.githubusercontent.com/3868028/129756008-0db740ea-5893-4347-b15e-479d8c7f3ca6.png">

The normal setting screen is much easier to read and understand
