### ISSUE TITLE
"Nothing Found" for series

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#143]
In the latest version, I'm getting "Nothing Found" for series URLs:

<img width="781" alt="Screen Shot 2021-08-16 at 2 01 53 PM" src="https://user-images.githubusercontent.com/3868028/129608893-36c9e36d-1fb4-4936-a6ad-4a179ae2c316.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , after debugging for a while, i noticed that page is the theme archive page for terms without content(e.g, category etc).

If you any series post, it'll show the series archive page.
