### ISSUE TITLE
Small design issues in metabox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#160]
Small design fixes: ![Screen Shot 2021-08-18 at 12 21 02 PM](https://user-images.githubusercontent.com/3868028/129935200-f86e0313-2fd0-456b-bcfc-ba10683defef.png)

Small text change: 

"A short title of this post that will be used in the Series widget. Leave blank to use the full title."

"If you leave this blank, this post will automatically be added to the end of the series."

**Comment by olatechpro** [comment]
@stevejburge , maybe you should explain better what the fix is as i made update to this in the last milestone just incase i didn't get you right

**Comment by stevejburge** [comment]
@olatechpro Sorry, in my version, all those extra spaces are still there. The request was to remove those spaces

**Comment by olatechpro** [comment]
> @olatechpro Sorry, in my version, all those extra spaces are still there. The request was to remove those spaces

Oh, I mistook it for adding spaces in last milestone. So, I end up add more 😂
