### ISSUE TITLE
Update button in Settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#161]
old:
<img width="342" alt="Screen Shot 2021-08-18 at 12 26 14 PM" src="https://user-images.githubusercontent.com/3868028/129935776-8fb13d4f-d104-4496-9096-5ad39e27746e.png">

new, to match PublishPress:
<img width="379" alt="Screen Shot 2021-08-18 at 12 26 08 PM" src="https://user-images.githubusercontent.com/3868028/129935799-49ba3e53-f398-4c7a-8e3f-c625a7dd3474.png">

**Comment by olatechpro** [comment]
I simply updated the button to these since they're update and reset button to avoid mistake 

![button](https://user-images.githubusercontent.com/46832636/130600081-58b0012e-639d-4bb8-9b34-49180f918215.jpg)
