### ISSUE TITLE
Improve CSS on frontend

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#162]
@htmgarcia maybe able to help.

Let's improve the appearance of the boxes on the frontend of the site:
<img width="1406" alt="Screen Shot 2021-08-18 at 12 38 58 PM" src="https://user-images.githubusercontent.com/3868028/129937749-7e48f522-76a0-495a-a4b8-1acda75fa55c.png">

This is the dark theme setting:
<img width="1220" alt="Screen Shot 2021-08-18 at 12 40 03 PM" src="https://user-images.githubusercontent.com/3868028/129937837-c06ede40-3061-4636-aedc-28716bdd649b.png">

And the light theme:
<img width="1239" alt="Screen Shot 2021-08-18 at 12 40 29 PM" src="https://user-images.githubusercontent.com/3868028/129937901-1fb9e67e-90de-496c-bee7-01147ed3393a.png">

**Comment by htmgarcia** [comment]
@stevejburge starter proposal https://github.com/publishpress/publishpress-series/commit/8d7ac3f4cef2f8a79c57aa5d24dfa1e1e6c3b5fa

![Screen Shot 2021-08-19 at 17 24 36](https://user-images.githubusercontent.com/4999794/130152279-c5060fb6-81dd-4c82-8cb4-568ae4d20a10.png)
![Screen Shot 2021-08-19 at 17 24 22](https://user-images.githubusercontent.com/4999794/130152281-af139dc1-d493-4cea-8e12-aa11adc68352.png)
![Screen Shot 2021-08-19 at 17 24 08](https://user-images.githubusercontent.com/4999794/130152284-e1156da0-7435-4f11-bf07-fb68a6b85071.png)

**Comment by stevejburge** [comment]
Thumbs up, thanks Valentin
