### ISSUE TITLE
All in SEO not working yet

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#166]
![Screen Shot 2021-08-18 at 2 52 34 PM](https://user-images.githubusercontent.com/3868028/129955633-0dd7b694-9be6-4227-a65a-4791a0a5335d.png)

**Comment by stevejburge** [comment]
Maybe it's just the banner needs hiding? We should move this to a new "All in One SEO" tab

![Screen Shot 2021-08-18 at 2 54 18 PM](https://user-images.githubusercontent.com/3868028/129955816-2a09a9a9-8e4e-4542-ac2d-2148962606cb.png)

**Comment by olatechpro** [comment]
All in SEO plugin has changed alot since this integration. So, the whole code and class implementation are no longer with the latest option.

Will have to test and update every part of integration and you can check for error too when you get it

**Comment by stevejburge** [comment]
@olatechpro I'm also OK with removing this. We can always save it for later
