### ISSUE TITLE
Changelog missing in readme.txt

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#168]

**Comment by olatechpro** [comment]
Hi @stevejburge , changelog history is completely not included in current plugin readme but the following note:
== Changelog ==

`Changelog is no longer bundled with the readme.  For latest commits see the [commit list on github](https://github.com/roughsmoothengine/organize-series/commits/master) or the [release tags](https://github.com/roughsmoothengine/organize-series/releases).  You can also view the [closed milestones on github](https://github.com/roughsmoothengine/organize-series/milestones?state=closed) to see what changed within a release.`

So, we'll be starting new changelog with next milestone ?

**Comment by stevejburge** [comment]
@olatechpro let's put the changelog back on WordPress.org and in the readme, please

**Comment by olatechpro** [comment]
> @olatechpro let's put the changelog back on WordPress.org and in the readme, please

Couldn't find previous changelog. So, we'll be starting with new changelog

**Comment by stevejburge** [comment]
Sound like a plan.

We can keep this text:

"For older commits, commits see the [commit list on Github](https://github.com/publishpress/publishpress-series/commits/master) or the [release tags](https://github.com/publishpress/publishpress-series/releases). You can also view the [closed milestones on github](https://github.com/publishpress/publishpress-series/milestones?state=closed) to see what changed within a release."
