### ISSUE TITLE
Make plugin translatable

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#186]
At the moment, it's not marked as translatable yet:
https://wordpress.org/plugins/organize-series/

**Comment by olatechpro** [comment]
Hi @stevejburge , where did you see this message ?

Can't find it

**Comment by olatechpro** [comment]
> @olatechpro That's the problem - it's missing.
> 
> Normally you can see the "Languages" option here:
> 
> <img alt="Screen Shot 2021-08-31 at 10 59 24 AM" width="378" src="https://user-images.githubusercontent.com/3868028/131526678-fdc04bf3-cf84-4b92-92cc-c6b5a10f8f57.png">
> 
> Here's PublishPress Capabilities:
> 
> <img alt="Screen Shot 2021-08-31 at 11 00 07 AM" width="393" src="https://user-images.githubusercontent.com/3868028/131526729-72268749-3d75-4c98-a501-af733eb26e89.png">

The reason that's the case is because the plugin is not translated into any language yet. 

I'll generate English language translation so it can have at least 1 language and add it now.
