### ISSUE TITLE
Can't add icon/image to a series

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#187]
1. Create a new series without adding an icon/image
2. Save
3. Edit the series created in step 1
4. Choose a "Series Icon Upload" image

An error in console come up:
```
Uncaught TypeError: wp.media is not a function
    <anonymous> /wp-content/plugins/organize-series//js/orgseries_scripts.js?ver=2.6.0:67
```

Update: Can't either add an image when creating a series (step 1)

Firefox 91.0.2
MacOS Big Sur 11.5.2

**Comment by olatechpro** [comment]
I'm unable to reproduce this issue on same browser and OS.

**Comment by htmgarcia** [comment]
Very odd. In a second try I can't reproduce the issue.

**Comment by olatechpro** [comment]
I just encountered this same issue now.

**Comment by htmgarcia** [comment]
Thanks @olatechpro !
