### ISSUE TITLE
Multiple series list overlays fields

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#188]
This needs a small design fix... or the purpose of these fields is to be hidden?
<img width="279" alt="Screen Shot 2021-08-26 at 14 00 10" src="https://user-images.githubusercontent.com/4999794/131020756-5406a0f5-f00c-45ea-9a9c-786469b15faa.png">

**Comment by olatechpro** [comment]
@stevejburge , for the records, i made additional improvement to this issue to match series meta box to other meta boxes

**Comment by stevejburge** [comment]
Awesome, thanks
