### ISSUE TITLE
"Group" feature needs a default output

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#202]
At the moment, you need to write code to use the Groups feature:
https://publishpress.com/knowledge-base/overview-groups/

**Comment by olatechpro** [comment]
I still need full direction on this issue implementation

**Comment by stevejburge** [comment]
Basically, the Groups feature does not work yet. There is no frontend display.

This is form the original developer: https://publishpress.com/knowledge-base/overview-groups/

`Inside the organize-series-grouping folder is a file labeled orgseries-grouping-template-tags.php.  Within this file are all the various tags that you can use to call and output the various Series Grouping data.  `

I think we should provide a working version for users. Otherwise, they will have to write code to use the Groups feature

**Comment by olatechpro** [comment]
...and what's the proposed UI like ?

**Comment by stevejburge** [comment]
@olatechpro good question. Let's see what we can do with orgseries-grouping-template-tags.php

I'm thinking possibly a grid. That is where we're going with the Series Overview:
https://github.com/publishpress/publishpress-series/issues/309

**Comment by olatechpro** [comment]
Well, my question is on content of the template. I read the linked issue but still doesn't understand it but if I have full description of what needed to be done, I'll be able to implement it.

For example, which link leads to the UI, is it from group taxonomy slug or a custom link and what's the content of the page or it's same as the series page content?

**Comment by stevejburge** [comment]
Group = Harry Potter
Series = Harry Potter Book 1, Harry Potter Book 2, Harry Potter Book 3, Harry Potter Book 4 etc

Group = Star Wars
Series = Return of the Jedi, Empire Strikes Back etc

This new feature will show "Harry Potter" and "Star Wars"

**Comment by olatechpro** [comment]
@stevejburge i've created the series group and series matching them to their group.
This new page you're talking about. Is it a custom link with ability for user to edit the slug same as the "Series Table of Contents URL" or link from the series group taxonomy page ? Will ask the last question on content after answering this.

<img width="1920" alt="Screenshot 2021-12-02 at 9 13 36 PM" src="https://user-images.githubusercontent.com/46832636/144495896-8c67d01b-9611-41b1-aa7b-0aa26a1ac7b8.png">
<img width="1920" alt="Screenshot 2021-12-02 at 9 13 27 PM" src="https://user-images.githubusercontent.com/46832636/144495941-a9fe2a42-dbd3-47b0-a908-db4646def6b4.png">

**Comment by olatechpro** [comment]
So, we'll be providing the link in settings like this which shows group series ?

![link](https://user-images.githubusercontent.com/46832636/144497503-3f7d3c02-0efa-499f-8104-53ecb2e4d4e5.jpg)

**Comment by stevejburge** [comment]
@olatechpro Yes, I'm open to a custom URL setting for this

Oddly, there is a "View" link in the "Groups" feature that goes to /series_group/my-group/. It just doesn't work yet:

![Screen Shot 2021-12-03 at 12 48 01 PM](https://user-images.githubusercontent.com/3868028/144649241-96fed628-80a6-4b77-8f61-19abed6fa530.png)

**Comment by olatechpro** [comment]
**Note:** the series group template can be customised by copying `'/plugins/publishpress-series-pro/includes-pro/addons/grouping/theme/primary/taxonomy-series_group.php'` to theme/child-theme directory
