### ISSUE TITLE
Use custom .css?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#205]
This should say "Use default .css?"

<img width="508" alt="Screen Shot 2021-09-02 at 12 40 02 PM" src="https://user-images.githubusercontent.com/3868028/131883484-81aa3bc4-8c33-4529-9128-55e53b6b8309.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , this is confusive.

Are you asking me to:
1.) Change 'Use custom .css?' to 'Use default .css?'
OR
2.) Append 'Use' in-front of the options like: 
- Use custom .css?
- Use dark themes ?
- Use light themes ?

**Comment by stevejburge** [comment]
Good questions. This box is confusing.

Maybe the label should be "Style options" and the choices are?

- Use default style
- Use light style
- Use dark style
- Disable all PublishPress CSS styles
