### ISSUE TITLE
Pro license key won't save

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#207]
Can confirm in my testing

> Hello, I just want to report an issue with the new Series Pro Plugin. When I enter my license in the plugin's license section, there is only the update options button to save it, but it doesnt change, it stays inactive in the status.

**Comment by olatechpro** [comment]
I try to recreate this issue on different browser but wasn't able to, this is how the license page is suppose to look with button to activate/deactivate license.

The only fix i made now is removing 'update' button on license page incase that's causing confusion.

The only reasonable reason that license button row could be missing is if there's a css on that same site hidden the row and as a result, may need more information to debug like inspecting element and checking console plug finding the element on page.

![licence-view](https://user-images.githubusercontent.com/46832636/132182580-8246dd9b-44c3-4219-bc6e-a0f5716a1733.jpg)
