### ISSUE TITLE
2.6.1 is causing a JavaScript error in core 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#213]
https://wordpress.org/support/topic/javascript-error-in-v2-6-1/

> Version 2.6.1 of this plugin is causing a JavaScript error in core when using the classic editor.
> 
> As part of the series metabox, this plugin creates a div with class categorydiv which is a special class used by core: https://github.com/WordPress/wordpress-develop/blob/b83b01e1b01429dc4a6da49ec23e1f7dfc4ae446/src/js/_enqueues/admin/post.js#L569-L571
> 
> The div is created by the plugin here: https://plugins.trac.wordpress.org/browser/organize-series/tags/2.6.1/orgSeries-admin.php#L288
> 
> Core’s JavaScript in post.js linked above does not expect this categorydiv class to be present anywhere except for in core’s category selector metabox. This plugin creates a div that breaks this core JavaScript code with an error “this_id is undefined”. This causes a cascading failure that stops much of the JavaScript execution on the editor page.
> 
> Removing the categorydiv class from this div seems to fix this error. I also see that the plugin code in trunk is different from what was released in 2.6.1 though, so I’m not sure if you had another fix in mind for this issue that didn’t make it into the 2.6.1 release.

**Comment by olatechpro** [comment]
This issue was fixed here #206
