### ISSUE TITLE
Series Grouping uses the default categories

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#216]
It should have it's own taxonomy:
<img width="583" alt="Screen Shot 2021-09-06 at 11 52 36 AM" src="https://user-images.githubusercontent.com/3868028/132242622-7a1b83ab-0e12-4fee-b472-f20892c203b1.png">
<img width="663" alt="Screen Shot 2021-09-06 at 12 04 32 PM" src="https://user-images.githubusercontent.com/3868028/132242643-84f088c9-359c-4d6b-9da1-eee3f5cdc9f9.png">

**Comment by stevejburge** [comment]
It seems we have a taxonomy (although the name may be an issue: https://github.com/publishpress/publishpress-series/issues/87)

But it's not being used:
![Screen Shot 2021-09-07 at 10 25 28 AM](https://user-images.githubusercontent.com/3868028/132361826-fadabe0b-6ff0-4ec7-aad0-c2f7069ad1f8.png)

**Comment by olatechpro** [comment]
It seems series grouping is not using category but rather updating category into series group taxonomy(will remove the option now) and also, series grouping is not the same as series taxonomy conflicting in issue you linked.
@stevejburge
