### ISSUE TITLE
Widgets are missing in the new Pro version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#218]
When installing the 2.6.2 Pro beta on sites (including TaxoPress.com), the two series widgets are missing

**Comment by olatechpro** [comment]
That's strange as it's showing here. Did you search for series ?
Maybe you should check your console for error and also, is this issue with just Pro or both version ?
![series-widget](https://user-images.githubusercontent.com/46832636/132319035-428a2f24-b036-4ac5-9bea-0754c56b73a6.jpg)

**Comment by stevejburge** [comment]
One more report of this:

> The problem is I do not see the Series widget in the blocks sidebar in the wordpress editor. I did find a couple of buttons in the hovering wordpress bar that appears inside the paragraph elements that says "Add OS Series post list box" and 3 more buttons for Series. but none of them do anything when I click on them, they dont add any widgets to the page content. Am I doing it right? Or how should I add this Series widgets?

**Comment by stevejburge** [comment]
I think this is an issue with widgets and Gutenberg.

On the troublesome site, I installed the Classic Widgets plugin: https://wordpress.org/plugins/classic-widgets/

With that, the widgets appeared.

**Comment by stevejburge** [comment]
One more report where it seems to appear in Elementor, but not core WordPress:

> In regards to the "Series Table of Contents" widget not showing up in elementor, you asked if this was only an issue in elementor. I looked for a "Series Table of Contents" block in the gutenberg editor and didn't see one. There is only a "Series Table of Contents" widget in elementor as far I can see, but it doesn't show up on the page.

**Comment by olatechpro** [comment]
I'm finally able to reproduce this after installing all the plugins you mentioned.
So, will make a fix now @stevejburge
