### ISSUE TITLE
Check dependabot alerts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#223]
https://github.com/publishpress/publishpress-series/security/dependabot

**Comment by htmgarcia** [comment]
@olatechpro to fix the dependabot alerts, in local update the npm modules that Github mention such as [path-parse](https://github.com/publishpress/publishpress-series/security/dependabot/package-lock.json/path-parse/open) by running `npm update <module-name>` to update to the latest version, or `npm update <module-name>@1.0.7 --save-dev` where 1.0.7 is the minimum version the dependabot suggest.

These changes will modify your package.json and package-lock.json. Once you commit this to Github, you can mark the dependabot "Dismiss" dropdown as "A fix has been already started".

Hopes this helps

**Comment by olatechpro** [comment]
Hi @stevejburge , the link 'https://github.com/publishpress/publishpress-series/security/dependabot' now shows 404 page, i don't know if something changes or i don't have permission to access it

**Comment by stevejburge** [comment]
@olatechpro Any better now?

**Comment by olatechpro** [comment]
Working now @stevejburge
