### ISSUE TITLE
Enable translations on WordPress.org

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#224]
<img width="363" alt="Screen Shot 2021-09-08 at 11 35 35 AM" src="https://user-images.githubusercontent.com/3868028/132540085-0571ec87-7f77-4cfa-bc98-fd0cd486f54f.png">

**Comment by olatechpro** [comment]
@stevejburge , i already did everything needed to be done codewise on this.

Is there problem with WordPress translator been able to translate the plugin or the plugin is not translateable on WordPress.org ?

The fact it didn't show any language could be as a result of the plugin yet to be translated into any language on WordPress.org or problem could be with the plugin slug which i'm only assuming as i'm not sure.
The plugin slug on wordpress.org is 'organize-series' and that's what we named the translation pot as well but plugin primary file is 'orgSeries.php'. That's the only strange thing but not sure if that could be the reason and we can't afford to rename the primary file name as doing so will deactivate the plugin after update which shows user will need to activate back after updating the plugin. So, don't want to do that unless we're sure it's the reason for the issue.

That aside, not sure of anything else needed to be done codewise
