### ISSUE TITLE
Clean up the release folder

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#227]
We don't need the /wp-assets/ folder with the WordPress.org banners

Are there other things we can remove?
<img width="218" alt="Screen Shot 2021-09-09 at 9 31 10 AM" src="https://user-images.githubusercontent.com/3868028/132695124-ba28db4f-291c-4dda-adbe-08db73f5a577.png">

**Comment by htmgarcia** [comment]
@olatechpro when making new releases you can skip "wp-assets" folder. This folder is safe to remove from the repository.

Not sure which method you use to push releases via SVN (terminal or with a particular application). Please let me know if you need help in this matter.

**Comment by olatechpro** [comment]
I use terminal. The folder has been there before we adopt the plugin. So, I'll just delete it from svn in next release
