### ISSUE TITLE
Fix numbering system in Pro

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#228]
Customer report:
<img width="801" alt="Screen Shot 2021-09-09 at 9 31 51 AM" src="https://user-images.githubusercontent.com/3868028/132695245-32227f19-9d2d-4dc8-b4a9-65948926e382.png">

Can confirm:
<img width="323" alt="Screen Shot 2021-09-09 at 9 27 34 AM" src="https://user-images.githubusercontent.com/3868028/132695272-bc70a2ac-df25-4836-b3f9-e5efcff53cb6.png">

**Comment by olatechpro** [comment]
Isn't this as a result of recent renaming new pro upload as publishpress-series-pro-2.61?

**Comment by stevejburge** [comment]
Yes, only the zip file needs the version number. The actual contents should not have the number

**Comment by htmgarcia** [comment]
@olatechpro small suggestion. First create the folder always named as "publishpress-series-pro"
Then compress that folder and include the version in the name. As example: "publishpress-series-pro_2.7.0.zip".
<img width="277" alt="Screen Shot 2021-09-09 at 10 20 41" src="https://user-images.githubusercontent.com/4999794/132714455-e3ff5e87-c95c-4f8e-aa18-5f5a5651d383.png">

**Comment by olatechpro** [comment]
That make sense, thanks @htmgarcia
