### ISSUE TITLE
Clarify "Series Table of Contents Listings"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#260]
What is this? Where does it appear?
<img width="940" alt="Screen Shot 2021-09-29 at 9 07 09 AM" src="https://user-images.githubusercontent.com/3868028/135274390-954b4d07-8ea4-4289-b34e-bf738533e437.png">

**Comment by olatechpro** [comment]
This is the description that was there before you asked me to remove them here #235

Should i add it back for the 2 or all ?
@stevejburge 
![des](https://user-images.githubusercontent.com/46832636/135278695-93badfce-c344-45e3-8368-0de2139c8c55.jpg)

**Comment by stevejburge** [comment]
@olatechpro Lol, I still don't understand even with that :)
