### ISSUE TITLE
Change current series order in series list

### ISSUE THREAD

**Issue by olatechpro** [publishpress/publishpress-series#289]
**Choose "3"**
- Previous post
- Current post
- Next post

**If you choose "5":**
- Previous post
- Previous post
- Current post
- Next post
- Next post

**Comment by olatechpro** [comment]
Hi @stevejburge , this application only apply to when limit is greater than series list right and no reorder of putting current in nth middle even when series list is equal or less than the limit ?

**Comment by stevejburge** [comment]
@olatechpro Yes, correct on both

- only when greater than the limit
- No reorder needed when equal or less than the limit
