### ISSUE TITLE
Undefined index in orgSeries-template-tags.php

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#296]
Another report from the same customer who reported https://github.com/publishpress/publishpress-series/issues/295

`[04-Nov-2021 12:27:05 UTC] PHP Notice:  Undefined index: series_table_of_contents_box_template in /home/ms101admin/public_html/wp-content/plugins/organize-series/orgSeries-template-tags.php on line 322`

**Comment by olatechpro** [comment]
This was as a result of #287 and we fixed it already
