### ISSUE TITLE
PHP Warning: include from /organize-series/vendor/composer/ClassLoader.php

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#297]
More from this customer: https://github.com/publishpress/publishpress-series/issues/296

A possible Yoast conflict?

`[04-Nov-2021 14:03:53 UTC] PHP Warning:  include(/home/ms101admin/public_html/wp-content/plugins/wordpress-seo/vendor/composer/../../admin/class-yoast-notification-center.php): failed to open stream: No such file or directory in /home/ms101admin/public_html/wp-content/plugins/organize-series/vendor/composer/ClassLoader.php on line 444`

**Comment by stevejburge** [comment]
@olatechpro No, this just came from the user's error logs

**Comment by olatechpro** [comment]
I don't know what the error is or able to recreate it.

**Comment by stevejburge** [comment]
OK, let's leave for now
