### ISSUE TITLE
Issue with "the_content" hook

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#306]
> Some themes render main blocks of their layout (header, content, footer) with "the_content" hook. Using the plugin with them leads to the series box displayed three times (in this particular case) or as many times that the_content hook was called on the page. In that case, the plugin need to be tweaked, so it can render the box content with another hook.

https://wordpress.org/support/topic/best-themes-to-use-organize-series/#post-15077924

**Comment by olatechpro** [comment]
@stevejburge, i'll need direction on what needed to be done here on the issues and expected result.

**Comment by stevejburge** [comment]
@olatechpro This user is pointing out that it may be bad idea for us to rely on the_content because it often loads multiple times.

Maybe we keep using the_content but find a way to only trigger it in the main post area?

**Comment by olatechpro** [comment]
Issues like this are better fixed when they can be seen. Can we get example
of themes with this issue to test ?

**Comment by olatechpro** [comment]
@stevejburge, while working on series group template, i realised another option to solve this issue is instead of hooking to the_content, we can render the series single in the own template from the plugin with option for users to copy the templete to their theme for customisation or completely opt out for it.

For now, i removed this issue from current milestone but if you give go ahead for this, we can add it back or leave it for now till we decided on best option

**Comment by stevejburge** [comment]
@olatechpro Sure thing, we can come back to this later

**Comment by stevejburge** [comment]
This is from the Beaver Builder team:

> We've looked into it on our end and it doesn't appear it is something we can do on our side.
> 
> Your plugin is hooking into the content and it's not something we adjust from within Themer.
> 
> If you could unhook your filter in the before and after header/footer hooks, that might work. But our developer believes your code would have to be modified first to make the class accessible via a global variable OR if by adding some sort of filter in the action to check if its enabled or disabled.
> 
> Hooks: fl_theme_builder_before_render_footer fl_theme_builder_after_render_footer fl_theme_builder_before_render_header fl_theme_builder_after_render_header

**Comment by olatechpro** [comment]
@stevejburge , i've removed our filter in 'fl_theme_builder_before_render_footer' and 'fl_theme_builder_before_render_header' and added it back in 'fl_theme_builder_after_render_footer' and 'fl_theme_builder_after_render_header'.

**Comment by olatechpro** [comment]
@stevejburge in addition, we introduced a filter  `apply_filters('pp_series_add_series_content', true)` which any other plugin developer to determine weather the series content should be display or not and that way, we give chance to other conflicting themes or plugins to fix the issue by returning false for our filter.
