### ISSUE TITLE
Allow users to customize buttons

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#311]
Can we add a new template option?

> How do I make a custom button for my PublishPress Series Pro navigational links.
> 
> To be more specific, how do I use HTML code to create a button that replaces the current text link, so that my webpage has custom buttons, and not a text link to the next, or previous post in a series.

Here's an example of what's required:
<img width="1388" alt="Screen Shot 2021-11-24 at 2 43 32 PM" src="https://user-images.githubusercontent.com/3868028/143303605-493c57b7-4f9c-4f82-8892-2180d695dd29.png">

**Comment by olatechpro** [comment]
What's the template name, token, and replacement value ?

**Comment by stevejburge** [comment]
@olatechpro  Maybe the solution is to allow images to be used in templates?

If we do that, users can add templates here:

<img width="971" alt="Screen Shot 2021-11-29 at 2 30 53 PM" src="https://user-images.githubusercontent.com/3868028/143930649-2df87298-d10d-4111-96ff-0fb6f584135b.png">

**Comment by olatechpro** [comment]
Okay, what currently needed to be done from my end since i don't think we current strip out images ?
@stevejburge

**Comment by stevejburge** [comment]
@olatechpro Can we confirm that IMG is allowed HTML? If so, let's add it to the sidebar
