### ISSUE TITLE
Add new tab or descriptions for URLs?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#319]
The new migration feature is causing a bit of confusion because we also have these other URL settings:

![Screen Shot 2021-11-30 at 5 01 53 PM](https://user-images.githubusercontent.com/3868028/144135752-6342a120-89d3-4871-95d9-ebcb7d1f1441.png)

I think maybe we should move "Series Custom Base" to be with the "Migration" / Taxonomy settings.

**Comment by olatechpro** [comment]
- "Series Custom Base" is moved to taxonomy tab in previous issue.
On the other request, i don't understand what you mean. We should add description to "series table of contents URL" ? If so, what's the description text ?
