### ISSUE TITLE
Series group missing when creating/editing series

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#324]
Have we lost the way to connect Series to Groups?
<img width="863" alt="Screen Shot 2021-12-06 at 11 03 28 AM" src="https://user-images.githubusercontent.com/3868028/144879832-77e2f6f7-cf6d-4aef-9474-857b16cb33be.png">
<img width="838" alt="Screen Shot 2021-12-06 at 11 03 12 AM" src="https://user-images.githubusercontent.com/3868028/144879836-03bb5f97-aa65-4b59-a011-4c817106c2b6.png">

**Comment by olatechpro** [comment]
@stevejburge did you test it on pro version and grouping addon is enabled ?

**Comment by stevejburge** [comment]
This a a Pro upgrade from 2.7.0 with Grouping enabled. Same as https://github.com/publishpress/publishpress-series/issues/324

**Comment by stevejburge** [comment]
@olatechpro Can confirm - this happens if you move to a new taxonomy

**Comment by olatechpro** [comment]
I can confirm this as a result of group addon using 'series' taxonomy and not new one and it's fixable
