### ISSUE TITLE
Can't add posts to Series 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#325]
Neither Quick Editor or the metabox is working

This for a site updated from 2.7

<img width="902" alt="Screen Shot 2021-12-06 at 11 05 31 AM" src="https://user-images.githubusercontent.com/3868028/144880258-591ff330-7d0a-4719-bec3-b2eae6eecc57.png">

**Comment by olatechpro** [comment]
Could something be wrong with your installation or probably messed things up with series taxonomy edit ? @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Can confirm - this happens if you move to a new taxonomy

**Comment by olatechpro** [comment]
I can confirm this as a result of group addon using 'series' taxonomy and not new one and it's fixable
