### ISSUE TITLE
Overview page layout description

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#346]
Sorry, no luck getting those to take effect in 2.7.1 

<img width="735" alt="Screen Shot 2021-12-10 at 2 24 06 PM" src="https://user-images.githubusercontent.com/3868028/145630297-659bdde0-e793-418b-b184-044d332151ca.png">

**Comment by htmgarcia** [comment]
@stevejburge this doc may clarify this scenario https://publishpress.com/knowledge-base/series-archive-templates/

**Comment by stevejburge** [comment]
@htmgarcia Thanks. We should update the text on this page then

**Comment by htmgarcia** [comment]
@stevejburge [the doc](https://publishpress.com/knowledge-base/series-archive-templates/) is already updated, however we can include an example to make it easier to understand.

**Comment by stevejburge** [comment]
@htmgarcia Sorry, I meant the text inside the plugin

**Comment by htmgarcia** [comment]
@stevejburge proposal:

![Screen Shot 2021-12-15 at 15 24 42](https://user-images.githubusercontent.com/4999794/146267324-50deed3b-fe7a-4060-9461-0f5d480433fa.png)

The description is displayed when choosing a layout different to "default" so the user can notice that blink and pay attention to the information.
![Screen Shot 2021-12-15 at 15 25 05](https://user-images.githubusercontent.com/4999794/146267345-4d2344e4-7808-4e3f-ac45-3b7611f99f39.png)

**Comment by stevejburge** [comment]
@htmgarcia looks great. For the second sentence, we can probably remove "In case the result doesn't match your theme design" and just have a link:
"Click here for details on how to customize these designs."

**Comment by htmgarcia** [comment]
@stevejburge update:
![Screen Shot 2021-12-16 at 17 23 30](https://user-images.githubusercontent.com/4999794/146463515-95a859a2-ced4-407d-9d48-98a22929ab88.png)

**Comment by stevejburge** [comment]
Awesome, thanks
