### ISSUE TITLE
Design for boxes is missing

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#352]
![Screen Shot 2021-12-15 at 17 06 29](https://user-images.githubusercontent.com/4999794/146470160-9cbfb92f-25a0-4e6d-816a-434506a618a0.png)

**Comment by stevejburge** [comment]
@htmgarcia Do you have any more details on this error?

**Comment by htmgarcia** [comment]
@stevejburge same result under PHP 5, 7 and 8. The issue remains after updating to 2.7.2. cc @olatechpro

**Comment by stevejburge** [comment]
Possibly related? https://github.com/publishpress/publishpress-series/issues/360

**Comment by htmgarcia** [comment]
@stevejburge no, is a different issue.

**Comment by olatechpro** [comment]
@htmgarcia , i didn't really know what changes as it wasn't working when you asked about it then  but the selected styles are now showing for series back.

![one](https://user-images.githubusercontent.com/46832636/149493046-8dbb16e2-59df-484a-bdbd-9edf10789e7f.jpg)
![two](https://user-images.githubusercontent.com/46832636/149493052-4112f9b8-5262-451a-897b-e14ad7f64474.jpg)

**Comment by olatechpro** [comment]
Due to issue with input sanitation that stripped out html tags from template, i had to reset option and maybe that's what fixed it, not sure but you can confirm from your end

**Comment by htmgarcia** [comment]
@olatechpro I tested with development branch and still see the issue.

**Comment by olatechpro** [comment]
I'm wondering why that's happening. I just tested on live website with current version on wordpress.org and it still produce result.

I'll leave this open till i'm able to understand while it may not work or not working.

![test](https://user-images.githubusercontent.com/46832636/149562260-09252500-7559-4758-add7-bfc40a547552.jpg)

**Comment by rami4625** [comment]
I also have this problem in my site:
https://elakademiapost.com/الدفن-السماوي،-كيف-يدفن-البوذيون-موتا/

![تعليق توضيحي 2022-01-18 201911](https://user-images.githubusercontent.com/39801266/149995743-a70a31fa-f0aa-446c-87d1-0d5852fa13f5.jpg)

**Comment by olatechpro** [comment]
@stevejburge can you try and see if you can recreate this issue on the last version sent to you. I asked to test on last version sent as the updated version on wordpress.org has issue with stripping out html in settings update.

**Comment by olatechpro** [comment]
Issued caused by #362 and should be working with update
