### ISSUE TITLE
Issues with new series layout

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#360]
> adding a new template in the latest update causing issues with the theme.
> In a version older than 2.7.1 the layout was coming from the theme itself. But now all layouts are broken and not compatible with the active theme. mainly Genesis Theme. 

There are a lot more details here: https://wordpress.org/support/topic/taxonomy-series-layout-issue/#post-15219536

**Comment by htmgarcia** [comment]
@stevejburge I added [a fix for the default layout](if (isset($this->settings['series_overview_page_layout']) && $this->settings['series_overview_page_layout'] !== 'default') {). 
@olatechpro may you include the fix in the next release, please?
