### ISSUE TITLE
HTML tags being stripped when saving

### ISSUE THREAD

**Issue by bjarne-ff** [publishpress/publishpress-series#362]
When you try to edit the output of the widgets any HTML tag will be deleted upon save. This causes a mess in the markup as everything is cluttered together with the actual post content and the outputtet widget cant be styles very easily.

**Comment by stevejburge** [comment]
Thanks @bjarne-ff. Can you be more specific ... "edit the output of the widgets"?

**Comment by bjarne-ff** [comment]
You know, if I wanna wrap “This post is part of…” in a div. I wrap everything in <div></div> with the fields in backend under Templates. But when saved things are stripped. The HTLM tags just disappear.

**Comment by stevejburge** [comment]
@bjarne-ff Thanks. Do you mean this "Term link format" box?

<img width="913" alt="Screen Shot 2022-01-10 at 10 49 26 AM" src="https://user-images.githubusercontent.com/3868028/148795634-04e8ce20-0d92-4f14-b0db-fc6f0a4a76c9.png">

If you can give specific details, we can solve this

**Comment by bjarne-ff** [comment]
This box

**Comment by stevejburge** [comment]
@bjarne-ff Can you send a screenshot of the code you're trying to enter? What tags are being stripped?

Sorry to be a pain, but developers need specific details to solve problems

**Comment by stevejburge** [comment]
OK, we got a second report with specifics. Before:
<img width="1483" alt="before" src="https://user-images.githubusercontent.com/3868028/148813974-1a5ba616-7ff3-425a-957a-56c998e35a6c.png">

After:
<img width="1154" alt="after" src="https://user-images.githubusercontent.com/3868028/148813986-cc07266a-86cc-4114-ab96-4888013cd565.png">

**Comment by bjarne-ff** [comment]
Just trying to wrap this part: 

Dette indlæg er del %series_part% af %total_posts_in_series% i serien %series_title_linked%%postcontent%

in <div></div>

When that part works, I’ll probably try more stuff, like adding a class to the div wrapper or wrap the links in another div.

**Comment by bjarne-ff** [comment]
Exactly!

**Comment by stevejburge** [comment]
Got it, thanks @bjarne-ff. Those details will be very helpful

**Comment by bjarne-ff** [comment]
Is there a fix for this?

**Comment by olatechpro** [comment]
@bjarne-ff , we're working to make the fix ready in next release but in the meantime, you can revert to previous version pending the time the release is available.

**Comment by bjarne-ff** [comment]
Cool, thanks!




*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent+with+Shift+Signature&utm_medium=Email+Signature&utm_content=General+Email+Group>*


Den ons. 12. jan. 2022 kl. 09.37 skrev Olawale Adesina <
***@***.***>:
