### ISSUE TITLE
Update (Series Table of Contents) code not working

### ISSUE THREAD

**Issue by rami4625** [publishpress/publishpress-series#369]
In latest version of plugin (2.7.2),
When I'm trying to update the code inside (Series Table of Contents) and save settings the code keep on it default state and not change.

![تعليق توضيحي 2022-01-18 202908](https://user-images.githubusercontent.com/39801266/149997176-56f713a4-e70b-40f9-bdda-38ee8dbc102b.jpg)

**Comment by olatechpro** [comment]
@stevejburge this is same issue as #362 and fixed

**Comment by olatechpro** [comment]
@rami4625 , update will be available soon and after updating the plugin, you can reset plugin option in series settings page to restore correct format.
