### ISSUE TITLE
Stop automatic re-numbering of posts within the series

### ISSUE THREAD

**Issue by Qara-Penimah** [publishpress/publishpress-series#376]
When updating the series number to achieve the correct order, the plugin renumbers other random posts in the series thus preventing me from ever getting the number sequence correct.

In order to achieve the correct sequence sometimes one or more posts might have the same number.

How can I change the series order if the plugin keeps updating the number randomly?

**Comment by birdbrainiac** [comment]
I'm finding the numbers change randomly too. It's a real pain, and considering the lack of response here, I may switch to another plugin. I'm definitely not going Pro.

**Comment by stevejburge** [comment]
@birdbrainiac I'm not sure if you're familiar with Github? This is a closed issue. You can see the related changes.

We added a setting to stop the automatic numbering.

**Comment by birdbrainiac** [comment]
@[stevejburge] I'm not too familiar with GitHub, no. I didn't notice it was a closed issue. If there is a change to automatic numbering coming, I'm very happy.
