### ISSUE TITLE
Better way to re-order posts in a series

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#377]
We may need to think about a better way for people to order a series. Should we have some kind of new improvement on the "Manage Series" screen?

Try doing a re-order from Quick Edit is not easy. Try getting the order correct with this set-up and it's difficult:

![Screen Shot 2022-01-25 at 11 16 50 AM](https://user-images.githubusercontent.com/3868028/151015720-5358390c-bc1f-4558-8d97-282226eb03d8.png)

**Comment by olatechpro** [comment]
@stevejburge thought we fixed this by allowing option to disable auto series order or do we have new suggestion to look into ?

**Comment by stevejburge** [comment]
@olatechpro True. I guess my thinking was this "Quick Edit" will be very slow on a big series, say with 30+ post. It may be better if there was a drag-and-drop option

Let's leave this for now and come back to it later

**Comment by olatechpro** [comment]
@stevejburge i don't understand why this was added. Is there something you want me to work on here that's not covered in https://github.com/publishpress/publishpress-series/issues/494?

**Comment by stevejburge** [comment]
@olatechpro Sorry, yes, this is a duplicate
