### ISSUE TITLE
Problem with Series Post List box and  %series_part%

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#382]
> I'm using the Series Post List box with this as the template:
> 
> %series_icon_linked%This article is part %series_part% of the series %series_title_linked%Series List:%post_title_list%
> 
> The problem is that %series_part% outputs [0] for each article in the series. Is there a way to fix this?

Can confirm:
![Screen Shot 2022-02-01 at 12 01 15 PM](https://user-images.githubusercontent.com/3868028/152014882-43f5ab5f-6b79-4ab3-bc7c-35eae1d805e6.png)

![Screen Shot 2022-02-01 at 12 00 26 PM](https://user-images.githubusercontent.com/3868028/152014898-86bfe57d-c66d-4f1a-a211-c42be2b6a2aa.png)

**Comment by olatechpro** [comment]
@stevejburge this problem happen with series post without part (this shouldn't be happening though unless the report is from the customer we sent recent changes that allow part assignment removal).

Will update the error message to signify this instead of part[0]
