### ISSUE TITLE
Advanced tab in the Free version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#391]
The name should be "Advanced", and let's add the renumbering option:

![Screen Shot 2022-02-03 at 12 31 37 PM](https://user-images.githubusercontent.com/3868028/152396806-3f4d4818-9e7f-44ab-a9fd-77f939f4ee90.png)

Current state:
![Screen Shot 2022-02-03 at 12 31 48 PM](https://user-images.githubusercontent.com/3868028/152396861-e6e79439-52a7-4d14-901d-8f23033ab7f3.png)

**Comment by olatechpro** [comment]
@stevejburge can you confirm the version on the plugin list ?

This setting you attached is outdated as this is my own screen

![free](https://user-images.githubusercontent.com/46832636/152398068-3ba36884-75ae-4805-b86b-5c8350c2cc5d.jpg)

**Comment by stevejburge** [comment]
Thanks. Solved
