### ISSUE TITLE
Improved design for Groups page

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#394]
Right now it hits the edges of the screen

![Screen Shot 2022-02-03 at 1 27 46 PM](https://user-images.githubusercontent.com/3868028/152405867-2f38c2d1-51a3-4d90-ad08-26fdba3c7c95.png)

**Comment by htmgarcia** [comment]
@olatechpro the groups page uses a custom template override from the plugin?

**Comment by stevejburge** [comment]
A custom template file, yes. I'm filling in the documentation now: https://publishpress.com/knowledge-base/overview-groups/

**Comment by htmgarcia** [comment]
@stevejburge what is the URL structure of this page and theme? 
![Screen Shot 2022-02-03 at 1 27 46 PM](https://user-images.githubusercontent.com/3868028/152405867-2f38c2d1-51a3-4d90-ad08-26fdba3c7c95.png)

**Comment by stevejburge** [comment]
@htmgarcia Grab the Pro version of Series. It's a Pro-only feature

**Comment by htmgarcia** [comment]
@stevejburge I'm sing pro, however I get a different result in my end:
![Screen Shot 2022-02-22 at 11 41 40](https://user-images.githubusercontent.com/4999794/155188100-c83c7243-c85d-44be-acd4-d3ad787d6bcf.png)

**Comment by htmgarcia** [comment]
@olatechpro opened 2 PRs 
https://github.com/publishpress/publishpress-series/pull/420
https://github.com/publishpress/publishpress-series-pro/pull/65

I can't fully test until we figure out #421
