### ISSUE TITLE
Improve design for Series taxonomy

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#395]
Related to https://github.com/publishpress/publishpress-series/issues/394

Choose "Grid" for example:
![Screen Shot 2022-02-03 at 1 30 58 PM](https://user-images.githubusercontent.com/3868028/152406357-91c9c2d6-d305-4228-be3f-a3687a1d3c06.png)

We hit the edge of the screen:

![Screen Shot 2022-02-03 at 1 29 58 PM](https://user-images.githubusercontent.com/3868028/152406441-4274d193-bca2-47a7-9f91-42004f9f442e.png)

**Comment by htmgarcia** [comment]
@stevejburge choosing a layout different to default will potentially result on the layout touching the edge due we override the theme archive/taxonomy template. More details: https://publishpress.com/knowledge-base/series-archive-templates/

**Comment by stevejburge** [comment]
@htmgarcia Thanks. Is there a way around this?

At the moment, our alternative options are difficult to use

**Comment by htmgarcia** [comment]
@stevejburge is complex to make our template work for all the themes. We can look for a way to make it compatible with the few core themes at least.

**Comment by stevejburge** [comment]
@htmgarcia Sound like a good plan, thanks
