### ISSUE TITLE
Series Post List Post Title (unpublished) Template:

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#401]
This feature controls unpublished posts.

We need a clearer name for this, and maybe a default setting.

Title: Series Post List Post Title (Unpublished)
Default: This Post is Coming Soon

Maybe all three need clarification:

- Series Post List Post Title (Current Post)
- Series Post List Post Title (Unpublished) 
- Series Post List Post Title (Linked Post)

<img width="774" alt="Screen Shot 2022-02-18 at 12 13 03 PM" src="https://user-images.githubusercontent.com/3868028/154730285-53448b6a-181a-4e91-9cc3-ad7e63239629.png">

**Comment by olatechpro** [comment]
@stevejburge , what's the third "Series Post List Post Title (Linked Post)" you're referring too ?

There seems to be just two Series Post List Post Title 

![spt](https://user-images.githubusercontent.com/46832636/155091168-fc25c6c2-7850-41c3-8537-d66fc185cae7.jpg)

**Comment by stevejburge** [comment]
@olatechpro These three are all tiny variations on the same thing:
![Screen Shot 2022-02-22 at 10 36 58 AM](https://user-images.githubusercontent.com/3868028/155166111-53971aea-e8c9-4aba-bc95-e04d9cd4960f.png)

**Comment by olatechpro** [comment]
Didn’t know how i skipped that 🤦🏽.

Seen now.

**Comment by stevejburge** [comment]
No worries. I'm still learning many parts of Series also

It has a lot of features that are very cool, but also unclear

**Comment by olatechpro** [comment]
@stevejburge Series Post List Post Title (Unpublished) actually has a default value but not properly updated and it's fixed now in coming commit.
