### ISSUE TITLE
Move the "Overview" tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#405]
Should this be moved?
<img width="698" alt="Screen Shot 2022-02-18 at 3 30 46 PM" src="https://user-images.githubusercontent.com/3868028/154757015-0737dcbb-6c6c-468f-adfd-32db88ec4175.png">

Should be more logically on the "Display" tab?

There are 3 displays (4 in the Pro version). They should have their own area under "Display":
https://publishpress.com/knowledge-base/displays-series/

**Comment by stevejburge** [comment]
Maybe "Series Base" belongs here too:
<img width="853" alt="Screen Shot 2022-02-18 at 4 22 32 PM" src="https://user-images.githubusercontent.com/3868028/154763030-e793f532-7015-4fe2-8bc6-91f2c5086790.png">

**Comment by stevejburge** [comment]
Alternative, maybe each display gets it own tab?

"Single Posts"
"Series Overview"
"All Series"

**Comment by olatechpro** [comment]
@stevejburge can you attach these new tabs content screenshot in settings, i don't know the content you're referring to as 'All series' tab ?

Also, you made mention of 

> "Maybe "Series Base" belongs here too:" 

So, what's your conclusion on that too, is it going to new tab or we're leaving it ?

**Comment by olatechpro** [comment]
@stevejburge can you attach these new tabs content screenshot in settings, i don't know the content you're referring to as 'All series' tab ?

Also, you made mention of 

> "Maybe "Series Base" belongs here too:" 

So, what's your conclusion on that too, is it going to new tab or we're leaving it ?

In addition, unless it's really necessary, i'll advise against adding tabs as the whole role is almost full with tabs already especially in PRO which may prevent us from adding more tabs when we need to or result in tabs going in two lines unless we think of another solution
