### ISSUE TITLE
Add Pro upgrade panels to Free

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#407]
Let's use the approach in PublishPress Authors and add upgrade screens to the Free version

- Groups
- Publish Series
- etc.

**Comment by olatechpro** [comment]
@stevejburge i'm wondering where these new menu will be, will it be as a submenu of series or exactly at their original places. For example, Groups and Publish Series are under posts ?

**Comment by stevejburge** [comment]
@olatechpro Good point. I guess we should put them under "Series"
