### ISSUE TITLE
Series taxonomy template header and footer deprecated in FSE themes

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#409]
When Overview page is different to default for Twenty Twenty-Two theme, the front displays 2 deprecated errors:
`Deprecated: Theme without header.php is <strong>deprecated</strong> since version 3.0.0 with no alternative available. Please include a header.php template in your theme. in /wp-includes/functions.php on line 5516`

**Comment by htmgarcia** [comment]
Related WP support ticket https://wordpress.org/support/topic/twenty-twenty-two-cpt-template-error-theme-without-header-is-deprecated/

**Comment by htmgarcia** [comment]
@olatechpro we have a challenge for our custom templates on Twenty Twenty-Two and other themes with Full Site Editing support. get_footer() and get_header() are not supported.

**Comment by olatechpro** [comment]
@htmgarcia i just read the linked article and i think considering the fact this is new, maybe our best option may be rendering our custom templates for themes that support it pending the time there's a stable solution since block theme works differently. 

I checked the documentation as well and rendering custom template may not be that easy but i'm still looking.

**Comment by olatechpro** [comment]
....on a further look, i don't think the way the new system is implemented, it may not be possible to render theme template in plugin. When i checked the Twenty Twenty-Two theme, the templating system has changed and even if we manage to find a way to render the default template in plugin, another check on another theme shows different themes template block data differs in implementation. Not sure if we'll find a solution anytime soon and in the meantime, maybe we can render the template for themes that support it ? 

I don't really know what out best option will be here. @htmgarcia

**Comment by htmgarcia** [comment]
We'll keep this on hold.
