### ISSUE TITLE
orgSeries-setup.php

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#419]
orgSeries-setup.php from free and pro are duplicated files with small differences.
@olatechpro should I manually implement improvements from free into pro? As example these changes: https://github.com/publishpress/publishpress-series/pull/410/files#diff-8465c2782cdbf232215b9910933d5074913db6f1b1b3d1088867929371e420b0

**Comment by olatechpro** [comment]
I’m yet to update pro with all free changes. You can commit your changes as
i’ll review all free version changes and update to pro when done.
