### ISSUE TITLE
Styling not working for group and toc pages

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#421]
The Style options are not being applied to group and toc pages, and/or the HTML outputted in frontend is different.

Based on the comparison below, the wrapper for the `<a>` tag is missing.

### HTML of groups page list when styling is working
```
<div class="serieslist-box">
    <div class="imgset"></div>
    <div class="serieslist-content">
        <h2>
            <a href="/series/sample-series/" class="series-3" title="Sample Series">Sample Series</a>
        </h2>
        <p></p>
    </div>
    <hr style="clear: left; border: none">
</div>
```

### HTML of groups page list when styling is NOT working
`<a href="/series/sample-series/" class="series-3" title="Sample Series">Sample Series</a>`

**Comment by htmgarcia** [comment]
@olatechpro the issue seems caused due the HTML tags were removed during saving process.

### Without HTML 
![Screen Shot 2022-02-22 at 15 40 12](https://user-images.githubusercontent.com/4999794/155224379-61b54396-7991-4689-a654-d38b54239ea1.png)

### With HTML - Expected result
![Screen Shot 2022-02-22 at 15 40 36](https://user-images.githubusercontent.com/4999794/155224395-90e4b7f2-45d4-4940-93bf-a49292e15087.png)

**Comment by htmgarcia** [comment]
I think this was fixed before. Please confirm.

**Comment by olatechpro** [comment]
Thanks @htmgarcia , i think that explain why it stopped working for me after updating settings. Checking it now

**Comment by olatechpro** [comment]
@htmgarcia that doesn't seems to be happening when i test now, wondering if it's as a result of the old issue and the page is yet to be updated ?

**Comment by htmgarcia** [comment]
@olatechpro in my end it was as result of the old issue.
