### ISSUE TITLE
Advanced tab has extra spacing in Pro

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#432]
This should be a label to the right:
"Delete all "Series Grouping" data from the database when deleting the plugin."

<img width="926" alt="Screen Shot 2022-03-04 at 12 04 32 PM" src="https://user-images.githubusercontent.com/3868028/156807921-7a0b7c58-fa45-4bd0-9e4b-161a9f9a2b17.png">

**Comment by stevejburge** [comment]
Sorry, still seeing this

**Comment by stevejburge** [comment]
Sorry, still there :)

**Comment by olatechpro** [comment]
@stevejburge i believe this was in error and can be closed right?

**Comment by stevejburge** [comment]
@olatechpro yes, sorry
