### ISSUE TITLE
Move series "Add New" metabox to html

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#433]
Setting:
<img width="418" alt="Screen Shot 2022-03-04 at 12 07 27 PM" src="https://user-images.githubusercontent.com/3868028/156808715-071b924f-d38d-48c4-8518-2b3978012b2c.png">

Result:

<img width="358" alt="Screen Shot 2022-03-04 at 12 07 00 PM" src="https://user-images.githubusercontent.com/3868028/156808743-cb1cb3aa-92bf-4063-8234-43f7f66bec12.png">

**Comment by olatechpro** [comment]
I just tested this again and it's working. I believe your current screenshot could be as a result of cache @stevejburge

**Comment by olatechpro** [comment]
@stevejburge i’m still waiting for your response on this issue to know if it closes or more information on it?

**Comment by stevejburge** [comment]
@olatechpro Yes, all good - thanks

**Comment by stevejburge** [comment]
Sorry, still seeing this

**Comment by olatechpro** [comment]
I strongly believe this a cache issue but i think i should just move the
add new button from javascript then since it’s giving problem.

So, hopefully, that should fix.
