### ISSUE TITLE
Consistent design for Settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#434]
Let's apply a consistent design to these tabs:

- "Post Types"
- "Icons"
- "Metabox"
- "Advanced"
- "Pro Features"

How about this for the layout
- Description on top of the screen
- Labels against the left side of the screen
- Checkboxes or entry boxes to right side of the screen

This is a clean out. Just needs the a description on top:
<img width="932" alt="Screen Shot 2022-03-04 at 12 15 44 PM" src="https://user-images.githubusercontent.com/3868028/156810550-069f3f88-f7f5-4821-901b-59a0421e55b7.png">

**Comment by olatechpro** [comment]
@stevejburge based on m understanding.
"Icons" > No changes required
"Metabox" > What should be the description?
"Advanced" > What should be the description?
"Pro Features" > What should be the description?

**Comment by stevejburge** [comment]
Thanks. 

Icons > Correct. Let's just use a regular font size for the description. Same as these:
![Screen Shot 2022-03-08 at 9 41 31 AM](https://user-images.githubusercontent.com/3868028/157260457-e02ff091-21ef-40e5-b530-654a8bd12953.png)

Metabox: These settings allow you to customize the metabox on the post editing screen.
Advanced: Please change these settings carefully as they make significant changes to PublishPress Series.
Pro Features: These settings allow you enable or disable features in PublishPress Series Pro.

**Comment by stevejburge** [comment]
@olatechpro 

Almost there.

"These settings allow you enable or disable features in PublishPress Series Pro."

![Screen Shot 2022-03-08 at 12 03 03 PM](https://user-images.githubusercontent.com/3868028/157288108-e83f05dc-8519-4d14-a8aa-5f60c7bfe585.png)

"Enable PublishPress Series for custom post types."

![Screen Shot 2022-03-08 at 12 03 45 PM](https://user-images.githubusercontent.com/3868028/157288292-609afdd4-a537-4284-b75d-c059ee5b5430.png)

"These templates allow you to customize the frontend appearance of PublishPress Series."

![Screen Shot 2022-03-08 at 12 04 56 PM](https://user-images.githubusercontent.com/3868028/157288595-7f9fd9b5-fca1-44b4-a56a-25ded198b7ef.png)

"These settings allow you to customize the main frontend screens in PublishPress Series."

![Screen Shot 2022-03-08 at 12 06 06 PM](https://user-images.githubusercontent.com/3868028/157288762-04fcfa16-41b9-417d-a75d-54c75691de7a.png)

New title: "Taxonomy"
Description: "This feature allows you to create a new taxonomy for this plugin to use if you don't want to use the default "Series"  taxonomy.
Under the box: "To create a new taxonomy, enter the new name and click the "Update Options" button.

![Screen Shot 2022-03-08 at 12 06 59 PM](https://user-images.githubusercontent.com/3868028/157289189-6f5b45bc-6b53-4ebf-87f0-4eaedff91b3c.png)
