### ISSUE TITLE
Screen after clicking "Publish"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#438]
/wp-admin/edit.php?page=manage-issues&action=list&series_ID=##

This screen needs some clean-up, please

- Space between "Publishing Series:" and series name
- Remove "Keep in mind that any Draft posts that are a part of this series will not show up in this list and will not be published"
- Remove the "Categories" column. Maybe replace with a "Preview" link?
- Can we update the style of the "Publish Issue" metabox to match 2022 WordPress?

<img width="1522" alt="Screen Shot 2022-03-04 at 12 29 10 PM" src="https://user-images.githubusercontent.com/3868028/156812609-a25da02f-d1a8-4ee1-8981-2fdb9a89b971.png">

**Comment by olatechpro** [comment]
@stevejburge can you be specific with the 2022 metabox issue, are you referring to publishing date not showing until user click on it or you’re referring a specific  styles that i’m probably not noticing ?

**Comment by stevejburge** [comment]
@olatechpro We can stay the old date picker, but I guess the new style metabox is more like this:


<img width="298" alt="Screen Shot 2022-03-04 at 12 40 07 PM" src="https://user-images.githubusercontent.com/3868028/156814090-beae9cb5-89ed-4010-9f8f-e4e8cafadcda.png">
