### ISSUE TITLE
Publish Series

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#449]
This screen looks a lot better. Some small changes, please:

- Text: "Unpublish posts in series" 
- Can we add a "Preview" link to the frontend?
- Can we have a column for Scheduled posts

![Screen Shot 2022-03-08 at 12 15 07 PM](https://user-images.githubusercontent.com/3868028/157290261-1523e373-48d0-4a4f-88cf-ed8e12992b08.png)

**Comment by olatechpro** [comment]
@stevejburge, everything works well for me.

what link are you getting for both the 
- Unpublished 
- View posts in admin ?
- 
i’m wondering if this could be the source of the problem.

so, you can paste the link for me to check

**Comment by stevejburge** [comment]
I'll do some more testing. Seeing some odd things that may be unique to my site

**Comment by stevejburge** [comment]
@olatechpro I've removed that item for now. I'll see if I can recreate it on another site

**Comment by olatechpro** [comment]
My comments are 2 on the issues. Both link you claimed not working may be working and per updated issue, it still has comment on view posts in admin link not working @stevejburge

**Comment by stevejburge** [comment]
@olatechpro Sorry, I'll remove that one also, unless I see it again
