### ISSUE TITLE
Using "Publish posts in series" produces a 0 for part number

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#454]
If I use the "Publish posts in series" link, this happens for Part numbers:
<img width="1319" alt="Screen Shot 2022-03-08 at 1 30 43 PM" src="https://user-images.githubusercontent.com/3868028/157302639-d50a55e1-3dc0-4a02-b587-572a25b07911.png">
<img width="1148" alt="Screen Shot 2022-03-08 at 1 29 43 PM" src="https://user-images.githubusercontent.com/3868028/157302651-8074ad50-96de-42ec-8c45-016eed1c710b.png">

**Comment by olatechpro** [comment]
**Note**: We should publish the part irrespective of what the user set in auto part settings.
