### ISSUE TITLE
Two issues with Series Table of Contents

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#465]
1. The "Series Table of Contents URL" doesn't work with default "Plain" WordPress permalinks
2. "Series Table of Contents <<" This is a strange header. How about we just use "All Series"

<img width="903" alt="Screen Shot 2022-03-15 at 12 43 30 PM" src="https://user-images.githubusercontent.com/3868028/158428735-e7879f3c-0aa4-4c5a-80f1-9e50d26ab8c0.png">

**Comment by olatechpro** [comment]
@stevejburge the first one is not an issue `The "Series Table of Contents URL" doesn't work with default "Plain" WordPress permalinks`  but limitation to use custom permalink. To use custom permalink, the user permalink has to be a custom or any permalink settings that allow slug and not just ?p=123. Example of this can be seen in Buddypress. If you install buddypress with plain permalink, you'll see notification to update the permalink for custom URL to work.
