### ISSUE TITLE
Custom Post Type Archive not working anymore

### ISSUE THREAD

**Issue by dreamon11** [publishpress/publishpress-series#474]
Since v2.7.2, the template **archive-$posttype.php** (Custom Post Type Archive) is not returned and displayed, the plugin PublishPress Series force by mistake the **archive.php** template.

It was working fine until v2.7.1.

Can you fix it?

Thanks!

**Comment by stevejburge** [comment]
Thanks for reporting that and for your PR, @dreamon11
