### ISSUE TITLE
Publish Series screen in Free version

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#478]
Let's increase the power of Series for Free users. 

Let's make the "Publish Series" screen available in the Free version

**Comment by olatechpro** [comment]
@stevejburge , i'm wondering if we should move publish series admin menu under series settings instead of it been under posts? It doesn't really have solid reason to be under post and will sit well under series settings as part of series?

**Comment by stevejburge** [comment]
@olatechpro I think that's a good idea, yes

For legacy users, maybe we have an option to include these under the "Posts" link

**Comment by stevejburge** [comment]
@olatechpro Maybe keep this idea around for a future update
