### ISSUE TITLE
Update "Series Groups" Menu title

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#495]
<img width="207" alt="Screen Shot 2022-04-14 at 3 07 36 PM" src="https://user-images.githubusercontent.com/3868028/163459543-48ef5caf-e26f-4070-8eec-b46a51d8f68e.png">

**Comment by olatechpro** [comment]
@stevejburge this is not self explanatory. "Series Groups" for Menu title? I don't understand what it mean.

**Comment by stevejburge** [comment]
Sorry, it's just missing a "s"

Old: Series Group
New: Series Groups
