### ISSUE TITLE
Allow Capabilities to support PublishPress Series

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#513]
This may be in the wrong repo, but let's add a PublishPress Series tab to Capabilities. 

At the moment, Series is stuck under "Additional"

<img width="579" alt="Screen Shot 2022-04-21 at 9 39 36 AM" src="https://user-images.githubusercontent.com/3868028/164470608-c5358d13-6f77-4aa6-84e4-37e42dbdd02c.png">

**Comment by olatechpro** [comment]
@stevejburge this issue seems to be outdated as at this moment, series has it own tab in capabilities

![series-tab](https://user-images.githubusercontent.com/46832636/174287988-42cdcace-6671-4cf5-acfb-0892b260096b.jpg)
