### ISSUE TITLE
Pages created with dynamic timeline content force series TOC to show even when not in a series

### ISSUE THREAD

**Issue by arretx** [publishpress/publishpress-series#530]
Latest version of plugin and wordpress as of today.

I'm using a theme called Ashe and I have Elementor installed as a layout plugin.

If I create a series, it appears to work correctly, where the series TOC is shown on a post that's part of the series.

When I create a new page that's not part of a series, it is displayed correctly, without any series TOC.  However, it seems that if I create a page in which there is dynamic post content, it forces the TOC to show up.

In this example, I've added a "Post Timeline" from the Elementor menu of goodies.  There are two modes for the timeline.  One is where you manually create timeline events INSIDE of the element, and the other is by selecting "Dynamic" in which case it pulls posts and displays the posts as the timeline items.  When I select Dynamic, the Series TOC shows up, even though the page that is hosting the dynamic timeline element is not part of a series.  Some of the posts IN the timeline ARE part of a series, but I'm just trying to create a timeline of posts without displaying the TOC for the Series plugin.

How could I fix this?

**Comment by arretx** [comment]
The section that's showing up is <div class="seriesbox"> and it's showing up because there's a <div class="post-content"> section on the page.

**Comment by stevejburge** [comment]
Hi @arretx 

Thanks for posting. Sorry, this area is for bugs in Series, not support or plugin compatibility issues.

We do have support options here: https://publishpress.com/publishpress-support/
