### ISSUE TITLE
Customize Posts Number in Series Page

### ISSUE THREAD

**Issue by rami4625** [publishpress/publishpress-series#536]
I want to select the posts number in page have link like this : website.com/series/seriesName
I know that i can use taxonomy-series.php to override the page but how can i customize the posts_per_page in the page query?

**Comment by stevejburge** [comment]
Hi @rami4625 

Sorry, GIthub issues are only for bugs, not general support.

Please see our support options here: https://publishpress.com/publishpress-support/
