### ISSUE TITLE
Can we add a Promo for PublishPress Blocks?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#541]
This will promote Blocks as the best way to showcase your series:

![Screen Shot 2022-06-16 at 3 58 37 PM](https://user-images.githubusercontent.com/3868028/174153988-d401d609-7455-4040-8b44-f851a3f1a07c.png)

![Screen Shot 2022-06-16 at 3 57 37 PM](https://user-images.githubusercontent.com/3868028/174153804-d98ca125-c105-4978-9d29-be0d5f29756f.png)

**Comment by olatechpro** [comment]
@stevejburge can you update the full text or it'll simply be:` "This will promote Blocks as the best way to showcase your series"`?

**Comment by stevejburge** [comment]
Label: Create beautiful layouts for your series

Bullets:
- PublishPress Blocks is 100% free to install and use.
- The Content Display block allows you to create advanced layouts for PublishPress Series
- Choose from Grid, List, Slider, Masonry, and other layouts.
