### ISSUE TITLE
Add Series and Series Group re-order field with term drag and drop feature

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/publishpress-series#584]
Allow to order all the series, and series inside groups.

**Comment by stevejburge** [comment]
Here's a good example: user will need to organize the series manually to fix something like this:

![Screen Shot 2022-08-11 at 1 56 18 PM](https://user-images.githubusercontent.com/3868028/184205125-9fcf18f4-a340-4e56-bf09-ce229fa374d5.png)
