### ISSUE TITLE
Remove new taxonomy metabox

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#595]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Series should be added to a new post
"When you go to create posts, you will now be able to add posts to your series, using the metabox"
https://publishpress.com/knowledge-base/installation-series/

## Current Behavior

Series are not being added to a new post 
## Steps to Reproduce (for bugs)

1. Posts
2. Add New
3. Add Title
4. In the widget area in 'Add New Series' type in Series
5. Press 'Publish'
6. Press 'W' on the upper left corner to navigate/wp-admin/ page
Series has not being added to a new post (see attachment below)
## Your Environment

* Version used: Version 2.9.2
* Browser Name and version: Chrome/Version 104.0.5112.101
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:
<img width="449" alt="Screen Shot 2022-08-29 at 8 15 19 PM" src="https://user-images.githubusercontent.com/107439940/188205725-6d47d791-0e11-4432-be42-f7db06857efd.png">
<img width="1984" alt="Screen Shot 2022-09-02 at 1 10 22 PM" src="https://user-images.githubusercontent.com/107439940/188205738-371f7573-4ffd-4355-bb07-06f3256b45f2.png">

**Comment by stevejburge** [comment]
This new box has appeared in recent versions of WordPress and we should hide it
