### ISSUE TITLE
Series title and text alignment error with 'Use box Style' option

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#598]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Series title and text should be properly aligned
## Current Behavior

Series title and text are too close to the left margin of the website
## Steps to Reproduce (for bugs)

1. Series
2. Settings
3. Under 'Display on single posts in a series' area in 'Style Options' select 'Use box style' radio button
4. Under 'Display on Series Table of Contents screens' select '1' radio button
5. Press 'Update Options'
6. View Site
Note: Series title and text alignment is too close to the left margin

## Your Environment

* Version used: Version 2.9.2
* Browser Name and version: Chrome/Version 104.0.5112.101
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:
<img width="790" alt="Screen Shot 2022-09-02 at 3 36 11 PM" src="https://user-images.githubusercontent.com/107439940/188228193-ef79600e-2f11-41a3-97fd-2337850ecb6c.png">

**Comment by olatechpro** [comment]
closing this for https://github.com/publishpress/publishpress-series/issues/600
