### ISSUE TITLE
Series title and text alignment error with 'Use dark style' option

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#599]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

Series title and text should be properly aligned on the website page
## Current Behavior

Series title and text are too close to the left margin of the website

## Steps to Reproduce (for bugs)

1. Series
2. Settings
3. Under 'Display on single posts in a series' area in 'Style Options' select 'Use dark style' radio button
4. Under 'Display on Series Table of Contents screens' select '1' radio button
5. Press 'Update Options'
6. View Site
Series title and text alignment is too close to the left margin 

## Your Environment

* Version used: Version 2.9.2
* Browser Name and version: Chrome/Version 104.0.5112.101
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:
<img width="1804" alt="Screen Shot 2022-09-02 at 3 48 05 PM" src="https://user-images.githubusercontent.com/107439940/188228984-a21f472b-1465-40ea-b79a-986c7279dc9c.png">

**Comment by olatechpro** [comment]
Closing this for https://github.com/publishpress/publishpress-series/issues/600
