### ISSUE TITLE
An existing post cannot be added to Series through 'Edit' option

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#602]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

An existing post should be able to be added to Series with 'Edit' option 
## Current Behavior

An existing post cannot be added to Series

## Steps to Reproduce (for bugs)

1. Posts
2. All Posts
3. Click on 'Edit' under an existing Post
4. In 'Add New Series' field enter a Series
5. Click 'Update'
6. Click on 'W' View Posts' in the upper left corner
Note: An existing post has not been added to a Series

## Your Environment

* Version used: Version 2.9.2
* Browser Name and version: Chrome / Version 104.0.5112.101
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:
<img width="688" alt="Screen Shot 2022-09-07 at 9 12 53 AM" src="https://user-images.githubusercontent.com/107439940/188890859-4e612bcc-06fb-4c51-9734-6d40ebc6708a.png">

**Comment by stevejburge** [comment]
This is the same as https://github.com/publishpress/publishpress-series/issues/595
