### ISSUE TITLE
Series text alignment issue with 'Use light style'

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#610]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Proper alignment of the Series on the page 

## Current Behavior
Series title and text are too close to the left margin of the website

## Steps to Reproduce (for bugs)

1. Series
2. Settings
3. Under 'Display on single posts in a series' area in 'Style Options' select 'Use light style' radio button
4. Press 'Update Options'
5. View Site
Note: Series title and text alignment are too close to the left margin of the website

## Your Environment

* Version used: Version 2.9.2
* Browser Name and version: Chrome / Version 104.0.5112.101
* Operating System and version (desktop or mobile): Macbook/ MacOs Catalina /Version 10.15.7
* Link to your project:

**Comment by stevejburge** [comment]
@mtlemissova Thanks. Is this the same as reported earlier? https://github.com/publishpress/publishpress-series/issues/600
