### ISSUE TITLE
Parts' numbering order issue is reproducible for the posts published earlier

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#632]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Parts numbering should start from the older posts to the newest 

## Current Behavior
Numbering is in ascending order (from newer posts to the oldest)

## Steps to Reproduce (for bugs)

1. Series Settings
2. Advanced
3. Check 'Enable automatic renumbering of posts in a series' -> Update Options
4. Posts -> All Posts
5. Select older post -> Edit Post 
6. In Series Metabox delete part number and leave Series part blank
7. Click 'Update' 
8. Click 'W' View Posts
9. Select another earlier published post -> 'Edit' -> Delete part number -> 'Update' -> 'View Posts'
Note: Numbering of parts is in ascending order

## Your Environment

* Version used: Version 2.9.2
* Browser Name and version: Chrome/Version 104.0.5112.101
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:

<img width="1793" alt="Screen Shot 2022-09-21 at 11 59 16 AM" src="https://user-images.githubusercontent.com/107439940/191553709-7c25c32e-3bb7-4267-bd61-ec409f7a0d48.png">

**Comment by olatechpro** [comment]
@stevejburge can you test this issue and confirm if something is not working the way they should?

In my testing, when new series are updated, irrespective of the post post published date, the series part is set as the last part if part is not provided and no re ordering parts in ascending or descending order.

**Comment by stevejburge** [comment]
@olatechpro I'm not seeing that in my testing. We can wait for another report

**Comment by mtlemissova** [comment]
I am sorry, but I attempted to delete part in each post and leave the 'Series part' edit field empty. The issue is still reproducible, even the issue with a negative input. Automatic renumbering of posts in a Series is enabled. Please see attached.


<img width="1795" alt="Screen Shot 2022-09-26 at 7 27 03 PM" src="https://user-images.githubusercontent.com/107439940/192398687-38d50c42-9c66-4ff4-b596-258c9b58890d.png">
