### ISSUE TITLE
"Series Categories" not "Groups" 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#650]
Some small text clean-up

2 here on the "Series" screen:
<img width="875" alt="Screen Shot 2022-09-29 at 2 24 58 PM" src="https://user-images.githubusercontent.com/3868028/193112985-e6339341-56f9-452b-88cb-f22964173800.png">

1 here on the "Series" screen:
<img width="493" alt="Screen Shot 2022-09-29 at 2 25 32 PM" src="https://user-images.githubusercontent.com/3868028/193113041-108867f7-6aeb-446c-8692-afac5946dd52.png">

2 here while editing a series:
<img width="864" alt="Screen Shot 2022-09-29 at 2 27 02 PM" src="https://user-images.githubusercontent.com/3868028/193113352-710ed364-3697-4254-8731-0f4242bbe9a2.png">

**Comment by olatechpro** [comment]
Fixed in https://github.com/publishpress/publishpress-series/pull/649
