### ISSUE TITLE
Series link in "Posts" table doesn't go anywhere

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#651]
This link should go to the Series but just goes to /wp-admin/edit.php?post_type=post

<img width="511" alt="Screen Shot 2022-09-29 at 2 29 22 PM" src="https://user-images.githubusercontent.com/3868028/193113797-d6da7ecd-693d-4016-992d-47a17d6c114c.png">

**Comment by olatechpro** [comment]
Fixed in https://github.com/publishpress/publishpress-series/pull/649
