### ISSUE TITLE
Fatal error for "Publish or schedule posts"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#652]
Click "Publish or schedule posts"
<img width="673" alt="Screen Shot 2022-09-29 at 2 32 45 PM" src="https://user-images.githubusercontent.com/3868028/193114424-cb459ca4-284e-4d5c-a1bc-e63719e7132f.png">

Get this error:
<img width="1116" alt="Screen Shot 2022-09-29 at 2 33 22 PM" src="https://user-images.githubusercontent.com/3868028/193114454-deec83da-690f-477d-bd91-6e3b0c007e42.png">

**Comment by olatechpro** [comment]
Fixed
