### ISSUE TITLE
Show "Series" in order on publishing screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#653]
Can we make two small changes here:
1) Show an "Order" column"
2) Organize the posts in order

<img width="978" alt="Screen Shot 2022-09-29 at 3 20 36 PM" src="https://user-images.githubusercontent.com/3868028/193123797-3cbef3ae-8fb4-4cfd-9c4e-72b0eb9c368c.png">

**Comment by olatechpro** [comment]
Fixed in https://github.com/publishpress/publishpress-series/pull/649
