### ISSUE TITLE
Text tweak for Success message:

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#654]
"Congratulations. Your posts were published successfully."

<img width="429" alt="Screen Shot 2022-09-29 at 3 23 47 PM" src="https://user-images.githubusercontent.com/3868028/193124089-50e704c7-b1b8-45e2-b2ec-308d1b0ba036.png">

**Comment by olatechpro** [comment]
Fixed in https://github.com/publishpress/publishpress-series/pull/649
