### ISSUE TITLE
Remove "Create as unpublished"?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#655]
I'm not sure this feature is working or is even useful:
<img width="594" alt="Screen Shot 2022-09-29 at 3 27 44 PM" src="https://user-images.githubusercontent.com/3868028/193124653-e348360a-7173-494d-b885-32614974fa20.png">

**Comment by olatechpro** [comment]
Fixed in https://github.com/publishpress/publishpress-series/pull/649
