### ISSUE TITLE
Two syntax errors in 'Series Table of Contents' widget field

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#671]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
"Table of Contents"

## Current Behavior
"Table of Content"

## Steps to Reproduce (for bugs)

1. Appearance
2. Widgets
3. Search for Series Widget
4. Open 'Series Table of Contents'
Note: Two syntax errors in "Show Series Table of Content" and "Show Series Table of Content as" (see attachment below)

## Your Environment

* Version used: Version 2.10.0
* Browser Name and version: Chrome/Version 105.0.5195.125
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:
<img width="663" alt="Screen Shot 2022-10-10 at 11 06 44 AM" src="https://user-images.githubusercontent.com/107439940/194901526-55c9d92c-c69c-4830-a66a-ff984eb9ac38.png">

**Comment by stevejburge** [comment]
@mtlemissova Thanks. Can you explain this more? A syntax error?

**Comment by mtlemissova** [comment]
A letter 's' is missing in word Content. Should be "Show Series Table of Contents"
Same pertains to "Show Series Table of Contents as:"

**Comment by stevejburge** [comment]
@mtlemissova Good catch, thanks!
