### ISSUE TITLE
An invalid form control with name=’series_part[0]’ is not focusable

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/publishpress-series#694]
When trying to save a post (in the Classic Editor), nothing happens, and the browser console shows this message

An invalid form control with name='series_part[0]' is not focusable.
```
<input class="small-text pp-series-part-input" min="1" type="number" name="series_part[0]" id="series_part" size="5" value="0" oninput="this.value = 
 !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null">
```

There’s no series linked to the post.

I’m on PHP 8.0, WordPress 6.0.3 and Series 2.10.0.

Looking at it again, I can see that the element series-part-wrap has an inline style display: none;, which hides the bottom part of the series sidebar widget, and makes its contents unfocusable.

If I manually disable this inline style, the box contains the number 0, and when trying to update the post, I get a validation error, saying the this isn’t a valid value for the field.

This is because of the attributes min="1" type="number" on the input field.

Posts with a series set can be updated, but posts without a series cannot.

Original thread: https://wordpress.org/support/topic/an-invalid-form-control-with-nameseries_part0-is-not-focusable/

**Comment by rizaardiyanto1412** [comment]
> After much investigation, I saw that orgSeries-admin.php sets the display of 3 elements to none based on plugin metabox settings, which are unchecked.
> 
> I don’t recall these settings from when I first configured the plugin. Are they new, and default to being unchecked?
> 
> But even when they are visible, I get a validation error when the series part is set to 0.
> 
> If I delete the 0, I can save the post, but then, the 0 comes back, along with the inability to save.
> 
> This seems to have been caused recently by this change: “Fixed: Only allow valid numbers in series part input #634”.

**Comment by galbaras** [comment]
Since 0 is a valid value, changing to `min="0"` should fix the validation issue.
