### ISSUE TITLE
Sorting series is not working

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/publishpress-series#696]
> My series are no longer in Name order. They appear to be in random order after a recent PublishPress update. Here is the shortcode that I have been using on my page: [series_toc orderby="name" order="ASC" hide_empty="false"] I have over 500 series so its now really hard for my members to find their Series. They have to scroll and scroll reading each Series title until they find their series - yikes! Thank you very much,

Ticket: [171154](https://secure.helpscout.net/conversation/2065732755/171154?folderId=2557461)

Issue happens on 2.10. Downgrade to 2.9.2 fix the sorting issue

**Comment by ijvg** [comment]
Seeing same issue on my site. Will try downgrading to 2.9.2 until resolved. 

using a similar shortcode: [series_toc orderby="slug" order="DESC"]
