### ISSUE TITLE
Add category_ids and series_ids to [series_post_categories]

### ISSUE THREAD

**Issue by olatechpro** [publishpress/publishpress-series#709]
@stevejburge We'll need documentation update for https://publishpress.com/knowledge-base/shortcode-publishpress_series_categories/ when this release is out.

- [series_post_categories] now accepts 2 new parameters

> `category_ids` [series_post_categories category_ids='23'] will limit the category out to only the category with ID 23. To include multiple category ID, use comma to seperate the ID. Example, [series_post_categories category_ids='23, 54']

> `series_ids` [series_post_categories series_ids='23'] will limit the category series to only series with ID 23. To include multiple series, use comma to seperate the ID. Example, [series_post_categories series_ids='23, 54']

**Comment by stevejburge** [comment]
@olatechpro I can do that. Thanks Ola
