### ISSUE TITLE
PHP warning PublishPress Series Pro v 2.10.1

### ISSUE THREAD

**Issue by Qara-Penimah** [publishpress/publishpress-series#723]
I am getting many of these warnings on the latest version:

Jan 08, 09:40:45
Warning: Undefined array key "post_series" in ...\wp-content\plugins\publishpress-series-pro\orgSeries-taxonomy.php on line 530

**Comment by stevejburge** [comment]
@Qara-Penimah Thanks. Can you send in a support ticket so we can debug this more, please?
