### ISSUE TITLE
Series Metabox is not showing alphabetical order

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/publishpress-series#729]
When you enable Multiple series
![image](https://user-images.githubusercontent.com/83811723/214200521-f4e193b0-9292-42fa-8c98-5cc5a88a32f9.png)

The metabox series on creating new post will not showing on alphabetical order

![image](https://user-images.githubusercontent.com/83811723/214200478-7974cfc4-0cd5-477c-ae84-266f731e0ab1.png)

Expected behavior:

It still showing alphabetical order even multiple series checked

**Comment by olatechpro** [comment]
The series term order will be fixed in https://github.com/publishpress/publishpress-series/issues/746
