### ISSUE TITLE
Post Types not applying metaboxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#776]
The Post Types tab appears:

<img width="568" alt="Screenshot 2023-05-25 at 10 05 23 AM" src="https://github.com/publishpress/publishpress-series/assets/3868028/443f9597-6ce2-411b-a795-5dc2c48a1cff">

But has no impact on the post type:
<img width="951" alt="Screenshot 2023-05-25 at 10 05 46 AM" src="https://github.com/publishpress/publishpress-series/assets/3868028/57ea25b4-0afc-4d3c-96c9-46bf6f0651a9">

**Comment by olatechpro** [comment]
Fixed
