### ISSUE TITLE
Multiple Series doesn't show part numbers correctly 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#791]
<img width="1099" alt="Screenshot 2023-06-05 at 8 07 35 AM" src="https://github.com/publishpress/publishpress-series/assets/3868028/2351ee9e-8b1b-4d2e-a500-f2cfdf898c4e">

**Comment by olatechpro** [comment]
@stevejburge Step on how you came across this issue will be helpful.
E.g, create new 3 series post, only one has a part number and for those without parts, they're not displaying correctly unless the issue is general
