### ISSUE TITLE
Quick edit post without part number

### ISSUE THREAD

**Issue by dapehe94** [publishpress/publishpress-series#811]
Hello
I have upgraded to PublishPress Series Free version 2.11.4 and now I cannot assign the series part number in quick edit of the post.

![image](https://github.com/publishpress/publishpress-series/assets/9955087/0eee7287-a1e1-4c1f-9495-3e4ce0f9293f)

In the previous version I was able to do it without any problem.

Thanks

**Comment by stevejburge** [comment]
@dapehe94 https://publishpress.com/blog/series/two-key-improvements-to-publishpress-series/
