### ISSUE TITLE
Add series metabox order settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#814]
One customer has been very insistent on this: could we add an ordering option? For example:

"Default Series Order"
"Alphabetical A-Z"
"Alphabetical Z-A"

<img width="582" alt="Screenshot 2023-06-21 at 10 40 28 AM" src="https://github.com/publishpress/publishpress-series/assets/3868028/0d2d9e70-f308-4423-9c0b-fca91bb040df">

**Comment by olatechpro** [comment]
@stevejburge Maybe we add the order filter on the Series Order screen itself?
Having series order in an order that's not by part number could possibly cause unwanted result for people that are looking to edit existing series.

I feel this feature is a one time usage than general settings?

**Comment by stevejburge** [comment]
Thanks @olatechpro Here's the ticket with more details https://secure.helpscout.net/conversation/2132926202/175417?folderId=2557461
