### ISSUE TITLE
Allow users to re-order drafts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#815]
From a customer who uses drafts heavily ... can we allow them to re-order drafts on the "Series Order" and "PublishPress or schedule posts" screens.

Maybe these screens need an additional "Update Order" button?

<img width="1440" alt="Screenshot 2023-06-21 at 4 51 08 PM" src="https://github.com/publishpress/publishpress-series/assets/3868028/f85c237b-5695-4a14-82e3-84571a4e5839">
<img width="1447" alt="Screenshot 2023-06-21 at 4 53 12 PM" src="https://github.com/publishpress/publishpress-series/assets/3868028/6f38ff54-d492-419a-88ab-dfb8a0306203">

**Comment by olatechpro** [comment]
@stevejburge Order is determined by part number and part number are not added to draft posts. Another solution will be adding another meta like part number for draft posts.

**Comment by stevejburge** [comment]
@olatechpro Good point. I wonder what the best solution is here?

Can we set an order in the "Unpublished posts" area?

**Comment by olatechpro** [comment]
Irrespective of the area, we need a new meta key equivalent to part key since unpublished post doesn't have part to set the order to. @stevejburge

**Comment by stevejburge** [comment]
Thanks @olatechpro. Yes, I think that makes sense, please
