### ISSUE TITLE
Do we need composer/installers as a requirement on composer.json?

### ISSUE THREAD

**Issue by andergmartins** [publishpress/publishpress-series#836]
When trying to install the plugin using composer, it returns the following error in the terminal:

```
Problem 1
    - publishpress/publishpress-series-pro[2.11.0, ..., 2.11.4] require composer/installers v1.0.6 -> found composer/installers[v1.0.6] but it conflicts with your root composer.json require (^2.2).
    - Root composer.json requires publishpress/publishpress-series-pro ^2.11 -> satisfiable by publishpress/publishpress-series-pro[2.11.0, 2.11.2, 2.11.3, 2.11.4].
```

I think we don't need the `composer/installers` as the plugin requirement since sites using composer will already have it listed as requirement.

**Comment by olatechpro** [comment]
Thanks @andergmartins composer/installers is no longer in the composer.json
