### ISSUE TITLE
Issue with Seriously Simple Podcasting plugin

### ISSUE THREAD

**Issue by eangulus** [publishpress/publishpress-series#87]
First, already posted in support for Seriously Simple Podcasting.

It's just a matter of whom can fix this first.

The plugin Seriously Simple Podcasting has a Series option for podcasts that seems to be the same as the Series for this plugin. Confirmed by changing a Podcast Series Name and it shows up in this plugin series list. Also, Series I have already created using this plugin are showing up as a Podcast series for Seriously Simple Podcasting.

**Comment by eangulus** [comment]
This is a very serious issue.

Have confirmed that Seriously SImple Podcast plugin also uses the series taxonomy.

Have been given an override to change that from my functions.php file, but is not quite complete as I get podcast information in the Manage Series page.

I am not sure who is really at fault here, but either way, I would have though that series is too generic to use as taxonomy and it would have been better to make that a little more precise like post-series or for podcasts podcast-series.

**Comment by olatechpro** [comment]
It seems series grouping is not using category but rather updating category into series group taxonomy(will remove the option now) and also, series grouping is not the same as series taxonomy conflicting in issue you linked.
@stevejburge

**Comment by stevejburge** [comment]
One more customer with this today.

Here's a clean site with both PublishPress Series and also Seriously Simple Podcasting plugin (I'm using TaxoPress). The Seriously Simple Podcasting plugin takes over the taxonomy:
<img width="1003" alt="Screen Shot 2021-11-09 at 4 32 33 PM" src="https://user-images.githubusercontent.com/3868028/141008478-35a57bde-5efb-4fb3-b6c6-d19ad4dfa107.png">

@olatechpro thoughts on how we work around this?

**Comment by olatechpro** [comment]
There's no work around other than changing series slug

@stevejburge

**Comment by stevejburge** [comment]
@olatechpro could we make this an option for individual sites, rather than a forced change for all our users?

**Comment by eangulus** [comment]
I think it should be a forced change. Using such a generic term as series, should not have been done in the backend. Why wasn't it ssp_series or something like that, in the code? You could still keep just Series on the front end. But if need be, give users a choice.

**Comment by olatechpro** [comment]
We can give option for the series slug but changing slug means they'll lose related series either new or old installation.

The only issue is the series slug is scattered inside the code and had to find everything and as well rely on user feedback after implementation incase it's left out on any part of the site since It won't make search for me to search series as the word is used all through the code even when it's not related to the main taxonomy slug.

So, changing is prone to error but if it's a must, we can go ahead with it and rely of user feedback.

@stevejburge

**Comment by stevejburge** [comment]
@eangulus I'd argue "series" makes a lot more sense for our plugin than theirs :) But that doesn't matter now.

@olatechpro I think giving the option makes sense. That way we don't risk breaking sites - the only people who will use this are people who expecting a significant change.

**Comment by olatechpro** [comment]
Cool @stevejburge

**Comment by olatechpro** [comment]
@stevejburge, we can as well offer migration option on the same screen where user set slug.

So, they can click a button to migrate all series to new slug.

I think that'll fix issue of having problem with existing series

**Comment by stevejburge** [comment]
Sounds good, thanks @olatechpro 

This is only for a small group of users, so a small solution is best

**Comment by olatechpro** [comment]
I don't really understand your last sentence.

Do you mean we shouldn't add the migrate button?
@stevejburge

**Comment by stevejburge** [comment]
@olatechpro Sorry, yes we should. 

Because it's only for a small group of users, it should be an option, not a default

**Comment by olatechpro** [comment]
Sure

**Comment by eangulus** [comment]
> @eangulus I'd argue "series" makes a lot more sense for our plugin than theirs :) But that doesn't matter now.
> 
> @olatechpro I think giving the option makes sense. That way we don't risk breaking sites - the only people who will use this are people who expecting a significant change.

I know it doesn't matter, but I wasn't saying it wasn't relevant. What I meant was that with coding, I have always started away from using generic terms, just in case it conflicted with something else. It also clearly shows what slugs belonged to what plugins.

On that note, how long before we may see a version that tries to fix this? I have mine working, some things are getting mixed up, but as I am the only one editing the site, I am aware and steer clear of those issues.

**Comment by olatechpro** [comment]
> > @eangulus I'd argue "series" makes a lot more sense for our plugin than theirs :) But that doesn't matter now.
> > @olatechpro I think giving the option makes sense. That way we don't risk breaking sites - the only people who will use this are people who expecting a significant change.
> 
> I know it doesn't matter, but I wasn't saying it wasn't relevant. What I meant was that with coding, I have always started away from using generic terms, just in case it conflicted with something else. It also clearly shows what slugs belonged to what plugins.
> 
> On that note, how long before we may see a version that tries to fix this? I have mine working, some things are getting mixed up, but as I am the only one editing the site, I am aware and steer clear of those issues.

New version will be available next week. It'll probably come through Monday/Tuesday after passing  testing as this involved changing all the slug usage to a single function with option for users to change the series slug.

**Comment by olatechpro** [comment]
@stevejburge , switching to dynamic slug for series results in some problem like series icon upload and column among others, will need more time to make sure everything is working fine with the dynamic and revert back if this won't really go through.
