### ISSUE TITLE
Can't translate taxonomy singular name

### ISSUE THREAD

**Issue by mrcasals** [publishpress/publishpress-series#92]
Hi!

I'm translating this plugin using the Loco Translate plugin. I've been able to translate the reader-facing strings, except for when I visit a series page, where the taxonomy keeps appearing in English. Here's the string I suspect I need to translate:

https://github.com/roughsmoothengine/organize-series/blob/b60ca1d41e37762e555d1f683f7f7debef93cac4/orgSeries-setup.php#L212

I'm checking the POT file of this plugin and it hasn't been updated for 8 years, so maybe the string is not there? Could you please update the POT file, @nerrad?

Thanks!

**Comment by mrcasals** [comment]
This seems to be fixed as of release 2.6.2 (maybe in 2.6.1, but I didn't check).

Thanks!

**Comment by stevejburge** [comment]
@mrcasals Yes, the string on WordPress.org should be good now
