### ISSUE TITLE
Add the PublishPress Footer

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#97]
<img width="536" alt="Screen Shot 2021-08-05 at 4 08 57 PM" src="https://user-images.githubusercontent.com/3868028/128414381-8d7376fb-867d-4101-a9a9-ec1c03bfcf8e.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , are we including manage series page in where PublishPress branding will be ?
This include the upgrade banner notice as well

![manage-series](https://user-images.githubusercontent.com/46832636/128891632-adefc8a7-9b2d-43a9-bdb4-f8a86e997322.jpg)

**Comment by stevejburge** [comment]
Yes, please @olatechpro
